/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controllers.AccountController;
import Controllers.MainController;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JLabel;

/**
 *
 * @author Naveed PC
 */
public class LoginRegister extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    private MainController system;
    private AccountController aC;
    private static final Color buttonColor = new Color(117, 59, 18);
    private static final Color buttonBorderColor = new Color(15, 6, 6);
    private static final Color buttonTextColor = new Color(220, 142, 0);
    private static final Color panelColor = new Color(199, 159, 79);
    private static final Color mainBackground = new Color(199, 159, 108);
    
    public LoginRegister(MainController system) throws SQLException {
        this.system = system;
        aC = new AccountController();
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        jButtonLogin.setBackground(buttonColor);
        jButtonLoginHere2.setBackground(buttonColor);
        jButtonRegister.setBackground(buttonColor);
        jButtonRegisterHere.setBackground(buttonColor);
        
        jButtonLogin.setBorder(BorderFactory.createLineBorder(buttonBorderColor));
        jButtonLoginHere2.setBorder(BorderFactory.createLineBorder(buttonBorderColor));
        jButtonRegister.setBorder(BorderFactory.createLineBorder(buttonBorderColor));
        jButtonRegisterHere.setBorder(BorderFactory.createLineBorder(buttonBorderColor));
        
        jButtonLogin.setForeground(buttonTextColor);
        jButtonLoginHere2.setForeground(buttonTextColor);
        jButtonRegister.setForeground(buttonTextColor);
        jButtonRegisterHere.setForeground(buttonTextColor);
        /*
        jLabelConfirmPassword2;
        jLabelDontHaveAcc;
        jLabelDontHaveAcc1;
        jLabelEmail2;
        jLabelFillInForm;
        jLabelFirstName2;
        jLabelLoginError;
        jLabelLoginTitle;
        jLabelPassword1;
        jLabelPassword2;
        jLabelPhone2;
        jLabelRegisterTitle;
        jLabelSurname2;
        jLabelUsername1;
        jLabelUsername2;
        */
        jPanelLoginBox.setBackground(panelColor);
        jPanelLoginPane.setBackground(mainBackground);
        jPanelRegisterBox.setBackground(panelColor);
        jPanelRegisterPane.setBackground(panelColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLoginPane = new javax.swing.JPanel();
        jPanelLoginBox = new javax.swing.JPanel();
        jLabelLoginTitle = new javax.swing.JLabel();
        jLabelUsername1 = new javax.swing.JLabel();
        jLabelPassword1 = new javax.swing.JLabel();
        jTextFieldUsername1 = new javax.swing.JTextField();
        jLabelDontHaveAcc = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jButtonRegisterHere = new javax.swing.JButton();
        jPasswordField3 = new javax.swing.JPasswordField();
        jLabelLoginError = new javax.swing.JLabel();
        jPanelRegisterPane = new javax.swing.JPanel();
        jPanelRegisterBox = new javax.swing.JPanel();
        jLabelRegisterTitle = new javax.swing.JLabel();
        jLabelUsername2 = new javax.swing.JLabel();
        jLabelPassword2 = new javax.swing.JLabel();
        jTextFieldUsername2 = new javax.swing.JTextField();
        jLabelDontHaveAcc1 = new javax.swing.JLabel();
        jButtonRegister = new javax.swing.JButton();
        jButtonLoginHere2 = new javax.swing.JButton();
        jLabelFillInForm = new javax.swing.JLabel();
        jLabelConfirmPassword2 = new javax.swing.JLabel();
        jTextFieldSurname2 = new javax.swing.JTextField();
        jLabelSurname2 = new javax.swing.JLabel();
        jLabelFirstName2 = new javax.swing.JLabel();
        jLabelEmail2 = new javax.swing.JLabel();
        jTextFieldEmail2 = new javax.swing.JTextField();
        jLabelPhone2 = new javax.swing.JLabel();
        jTextFieldPhone2 = new javax.swing.JTextField();
        checkboxTerms2 = new java.awt.Checkbox();
        jTextFieldFirstName2 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField1 = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(900, 550));
        setLayout(new java.awt.CardLayout());

        jPanelLoginPane.setPreferredSize(new java.awt.Dimension(900, 550));

        jPanelLoginBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelLoginBox.setPreferredSize(new java.awt.Dimension(700, 425));

        jLabelLoginTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelLoginTitle.setText("Login");

        jLabelUsername1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelUsername1.setText("Username:");

        jLabelPassword1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPassword1.setText("Password:");

        jLabelDontHaveAcc.setText("Don't have an account?");

        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jButtonRegisterHere.setText("Register Here");
        jButtonRegisterHere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterHereActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLoginBoxLayout = new javax.swing.GroupLayout(jPanelLoginBox);
        jPanelLoginBox.setLayout(jPanelLoginBoxLayout);
        jPanelLoginBoxLayout.setHorizontalGroup(
            jPanelLoginBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginBoxLayout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addGroup(jPanelLoginBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginBoxLayout.createSequentialGroup()
                        .addGroup(jPanelLoginBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLoginBoxLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabelLoginError, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelLoginBoxLayout.createSequentialGroup()
                                .addGroup(jPanelLoginBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelUsername1)
                                    .addComponent(jLabelPassword1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelLoginBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldUsername1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                    .addComponent(jPasswordField3)
                                    .addComponent(jButtonLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanelLoginBoxLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jButtonRegisterHere, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(243, 243, 243))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginBoxLayout.createSequentialGroup()
                        .addComponent(jLabelDontHaveAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(217, 217, 217))))
            .addGroup(jPanelLoginBoxLayout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(jLabelLoginTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLoginBoxLayout.setVerticalGroup(
            jPanelLoginBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLoginTitle)
                .addGap(100, 100, 100)
                .addGroup(jPanelLoginBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsername1)
                    .addComponent(jTextFieldUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLoginBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword1)
                    .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelLoginError, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jLabelDontHaveAcc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRegisterHere, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanelLoginPaneLayout = new javax.swing.GroupLayout(jPanelLoginPane);
        jPanelLoginPane.setLayout(jPanelLoginPaneLayout);
        jPanelLoginPaneLayout.setHorizontalGroup(
            jPanelLoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelLoginBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        jPanelLoginPaneLayout.setVerticalGroup(
            jPanelLoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelLoginBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        add(jPanelLoginPane, "card2");

        jPanelRegisterPane.setPreferredSize(new java.awt.Dimension(900, 550));

        jPanelRegisterBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelRegisterBox.setPreferredSize(new java.awt.Dimension(700, 425));

        jLabelRegisterTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelRegisterTitle.setText("Register");

        jLabelUsername2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelUsername2.setText("Username:");

        jLabelPassword2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPassword2.setText("Password:");

        jLabelDontHaveAcc1.setText("Already have an account?");

        jButtonRegister.setText("Register");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });

        jButtonLoginHere2.setText("Login Here");
        jButtonLoginHere2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginHere2ActionPerformed(evt);
            }
        });

        jLabelFillInForm.setText("Fill in the following form:");

        jLabelConfirmPassword2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelConfirmPassword2.setText("Confirm Password:");

        jLabelSurname2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSurname2.setText("Surname:");

        jLabelFirstName2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFirstName2.setText("First Name:");

        jLabelEmail2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEmail2.setText("Email Address:");

        jLabelPhone2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPhone2.setText("Phone Number:");

        checkboxTerms2.setLabel("I accept terms and conditions");
        checkboxTerms2.setName(""); // NOI18N

        javax.swing.GroupLayout jPanelRegisterBoxLayout = new javax.swing.GroupLayout(jPanelRegisterBox);
        jPanelRegisterBox.setLayout(jPanelRegisterBoxLayout);
        jPanelRegisterBoxLayout.setHorizontalGroup(
            jPanelRegisterBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegisterBoxLayout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(checkboxTerms2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelRegisterBoxLayout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addGroup(jPanelRegisterBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelDontHaveAcc1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLoginHere2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegisterBoxLayout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addGroup(jPanelRegisterBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegisterBoxLayout.createSequentialGroup()
                        .addComponent(jLabelRegisterTitle)
                        .addGap(295, 295, 295))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegisterBoxLayout.createSequentialGroup()
                        .addComponent(jLabelFillInForm)
                        .addGap(287, 287, 287))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegisterBoxLayout.createSequentialGroup()
                        .addGroup(jPanelRegisterBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelRegisterBoxLayout.createSequentialGroup()
                                .addComponent(jLabelConfirmPassword2)
                                .addGap(18, 18, 18)
                                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRegisterBoxLayout.createSequentialGroup()
                                .addGroup(jPanelRegisterBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelUsername2)
                                    .addComponent(jLabelPassword2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelRegisterBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldUsername2, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(jPasswordField1)))
                            .addGroup(jPanelRegisterBoxLayout.createSequentialGroup()
                                .addComponent(jLabelSurname2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldSurname2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRegisterBoxLayout.createSequentialGroup()
                                .addComponent(jLabelFirstName2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldFirstName2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRegisterBoxLayout.createSequentialGroup()
                                .addComponent(jLabelPhone2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRegisterBoxLayout.createSequentialGroup()
                                .addComponent(jLabelEmail2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(239, 239, 239))))
        );
        jPanelRegisterBoxLayout.setVerticalGroup(
            jPanelRegisterBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegisterBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRegisterTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelFillInForm)
                .addGap(18, 18, 18)
                .addGroup(jPanelRegisterBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsername2)
                    .addComponent(jTextFieldUsername2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegisterBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegisterBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConfirmPassword2)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegisterBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFirstName2)
                    .addComponent(jTextFieldFirstName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegisterBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSurname2)
                    .addComponent(jTextFieldSurname2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegisterBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail2)
                    .addComponent(jTextFieldEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegisterBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhone2)
                    .addComponent(jTextFieldPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkboxTerms2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabelDontHaveAcc1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLoginHere2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanelRegisterPaneLayout = new javax.swing.GroupLayout(jPanelRegisterPane);
        jPanelRegisterPane.setLayout(jPanelRegisterPaneLayout);
        jPanelRegisterPaneLayout.setHorizontalGroup(
            jPanelRegisterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegisterPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelRegisterBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        jPanelRegisterPaneLayout.setVerticalGroup(
            jPanelRegisterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegisterPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelRegisterBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        add(jPanelRegisterPane, "card3");
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Registers the customer.
     */
    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        if(jPasswordField1.getText().equals(jPasswordField2.getText())
                && checkboxTerms2.getState() && !jPasswordField1.getText().equals("")){
            try {
                aC.registerCustomer(jTextFieldFirstName2.getText(), jTextFieldSurname2.getText(),
                        jTextFieldEmail2.getText(), jTextFieldUsername2.getText(),
                        jPasswordField1.getText(), jTextFieldPhone2.getText());
                redirectLogin();
            } catch (SQLException ex) {
                Logger.getLogger(LoginRegister.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jButtonLoginHere2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginHere2ActionPerformed
        redirectLogin();
    }//GEN-LAST:event_jButtonLoginHere2ActionPerformed

    private void jButtonRegisterHereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterHereActionPerformed
        jPanelLoginPane.removeAll();
        jPanelLoginPane.repaint();
        jPanelLoginPane.revalidate();
        jPanelLoginPane.add(jPanelRegisterBox);
        jPanelLoginPane.repaint();
        jPanelLoginPane.revalidate(); 
    }//GEN-LAST:event_jButtonRegisterHereActionPerformed

    /**
     * Logs the user in.
     */
    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        aC.login(jTextFieldUsername1.getText(), jPasswordField3.getText(), system, this);
    }//GEN-LAST:event_jButtonLoginActionPerformed

    public void redirectLogin(){
        jPanelLoginPane.removeAll();
        jPanelLoginPane.repaint();
        jPanelLoginPane.revalidate();
        jPanelLoginPane.add(jPanelLoginBox);
        jPanelLoginPane.repaint();
        jPanelLoginPane.revalidate(); 
    }
    
    public JLabel getJLabelLoginError(){
        return jLabelLoginError;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox checkboxTerms2;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonLoginHere2;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jButtonRegisterHere;
    private javax.swing.JLabel jLabelConfirmPassword2;
    private javax.swing.JLabel jLabelDontHaveAcc;
    private javax.swing.JLabel jLabelDontHaveAcc1;
    private javax.swing.JLabel jLabelEmail2;
    private javax.swing.JLabel jLabelFillInForm;
    private javax.swing.JLabel jLabelFirstName2;
    private javax.swing.JLabel jLabelLoginError;
    private javax.swing.JLabel jLabelLoginTitle;
    private javax.swing.JLabel jLabelPassword1;
    private javax.swing.JLabel jLabelPassword2;
    private javax.swing.JLabel jLabelPhone2;
    private javax.swing.JLabel jLabelRegisterTitle;
    private javax.swing.JLabel jLabelSurname2;
    private javax.swing.JLabel jLabelUsername1;
    private javax.swing.JLabel jLabelUsername2;
    private javax.swing.JPanel jPanelLoginBox;
    private javax.swing.JPanel jPanelLoginPane;
    private javax.swing.JPanel jPanelRegisterBox;
    private javax.swing.JPanel jPanelRegisterPane;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField jTextFieldEmail2;
    private javax.swing.JTextField jTextFieldFirstName2;
    private javax.swing.JTextField jTextFieldPhone2;
    private javax.swing.JTextField jTextFieldSurname2;
    private javax.swing.JTextField jTextFieldUsername1;
    private javax.swing.JTextField jTextFieldUsername2;
    // End of variables declaration//GEN-END:variables
}
